on:
  pull_request:
  push:
      branches: using_java17
jobs:
  temurin:
    strategy:
      matrix:
        os: [ubuntu-latest,macos-latest]
        java: [17]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
      - name: Execute Gradle build
        run: ./gradlew clean :library:testDebugUnitTest
        env:
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_API_KEY }}
          AGENT_JAVA_VERSION: "${{ matrix.java }}-temurin"
